INSERT INTO provinces(id,name,slug,country_id) VALUES (1,'آذربایجان شرقی','آذربایجان-شرقی',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (2,'آذربایجان غربی','آذربایجان-غربی',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (3,'اردبیل','اردبیل',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (4,'اصفهان','اصفهان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (5,'البرز','البرز',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (6,'ایلام','ایلام',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (7,'بوشهر','بوشهر',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (8,'تهران','تهران',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (9,'چهارمحال و بختیاری','چهارمحال-بختیاری',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (10,'خراسان جنوبی','خراسان-جنوبی',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (11,'خراسان رضوی','خراسان-رضوی',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (12,'خراسان شمالی','خراسان-شمالی',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (13,'خوزستان','خوزستان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (14,'زنجان','زنجان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (15,'سمنان','سمنان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (16,'سیستان و بلوچستان','سیستان-بلوچستان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (17,'فارس','فارس',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (18,'قزوین','قزوین',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (19,'قم','قم',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (20,'کردستان','کردستان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (21,'کرمان','کرمان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (22,'کرمانشاه','کرمانشاه',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (23,'کهگیلویه و بویراحمد','کهگیلویه-بویراحمد',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (24,'گلستان','گلستان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (25,'لرستان','لرستان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (26,'گیلان','گیلان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (27,'مازندران','مازندران',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (28,'مرکزی','مرکزی',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (29,'هرمزگان','هرمزگان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (30,'همدان','همدان',105);
INSERT INTO provinces(id,name,slug,country_id) VALUES (31,'یزد','یزد',105);
